name: allodocteur
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  chewie: ^1.7.4
  video_player: ^2.8.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  email_validator: ^2.1.17
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:

    - family: gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500

  assets:
    - assets/images/
    - assets/icons/

    
