// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjDNtxoFZ_bn2A42SOtKCp_NIDXdVh54',
    appId: '1:45943979072:web:70b76adb3f3e3b028133a5',
    messagingSenderId: '45943979072',
    projectId: 'doctolo-3ee9a',
    authDomain: 'doctolo-3ee9a.firebaseapp.com',
    storageBucket: 'doctolo-3ee9a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaJyAQ72lodx75Oy6Lmhos0Sinkge0ywM',
    appId: '1:45943979072:android:b41b6f13b37b10db8133a5',
    messagingSenderId: '45943979072',
    projectId: 'doctolo-3ee9a',
    storageBucket: 'doctolo-3ee9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5hXqYz8FUTyO3FnXYQp_3xgSrftMgS-0',
    appId: '1:45943979072:ios:9f193b4f871de3d48133a5',
    messagingSenderId: '45943979072',
    projectId: 'doctolo-3ee9a',
    storageBucket: 'doctolo-3ee9a.appspot.com',
    iosBundleId: 'com.example.doctolo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5hXqYz8FUTyO3FnXYQp_3xgSrftMgS-0',
    appId: '1:45943979072:ios:ffa3fb02611dff808133a5',
    messagingSenderId: '45943979072',
    projectId: 'doctolo-3ee9a',
    storageBucket: 'doctolo-3ee9a.appspot.com',
    iosBundleId: 'com.example.doctolo.RunnerTests',
  );
}
