name: doctolopro
description: revelotion project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  animated_splash_screen: ^1.3.0
  google_nav_bar: ^5.0.6
  google_fonts: ^5.1.0
  cloud_firestore: ^4.11.0
  firebase_auth: ^4.8.0
  email_validator: ^2.1.17
  flutter_svg: ^2.0.7 
  carousel_slider: ^4.2.1
  get: ^4.6.5
  flutter_windowmanager: ^0.2.0
  html: ^0.15.4
  firebase_messaging: 14.7.10
  firebase_database: ^10.4.9
  flutter_osm_plugin: ^0.70.4
  numberpicker: ^2.1.2
  flutter_spinkit: ^5.2.1
  image_picker: ^1.0.8
  firebase_storage: ^11.6.9
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  flutter_mapbox_navigation: ^0.2.2
  geolocator: ^11.1.0
  url_launcher: ^6.3.0
  shared_preferences: ^2.2.3
sizer: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1

flutter_icons:
    android: true
    ios: true
    image_path: assets/images/doctolo_logo.png
    adaptive_icon_foreground: 'assets/images/doctolo_logo.png'
    adaptive_icon_background: '#ffffff'
    remove_alpha_ios: true
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - assets/gif/

  fonts:
    - family: gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500



